### ISSUE TITLE
Support for 24V LED

### ISSUE THREAD

**Issue by hnykda** [tjclement/esp-dimmer-hardware#12]
Hey. I am really excited about this project as I want to be able to individually control many different light strips in my home run in parallel in different temperatures.

I have two questions:

1. can the board be edited in a way that it supports 24V LED strips or do I need some buck converter (which would be pretty annoying if I had to do it for each channel individually)?
2. I really just order it from http://dirtypcbs.com/store/designer/details/tjclement/1329/5-esp8266-rgb-led-dimmer (e.g. in 10 pieces), buying parts from e.g. aliexpress, solder it on the board, use ESPHome to flash it (after connecting it via serial-to-USB to PC)  and then I am done? Living a dream :scream: .

Thanks for an amazing work!

**Comment by tjclement** [comment]
Hey, thanks for reaching out. Cool to see you're interested in making some!

To answer your questions:

1. In theory the FDS8896 mosfet can handle 24V just fine, although the MP2307 buck converter is listed as 23V max input. I've not tested at 24V; you could try your luck and see if it works.

At the least it's assumable that the lifespan of the buck converter is reduced when you feed it 24V, although whether I don't know whether it'll be significant. You could also try to find alternative buck converters for which 24V is within their operating range, and e.g solder them to the board with. wires.

2. Yep, that's it. The components you'll need are on the main readme in this repository: 
![image](https://user-images.githubusercontent.com/5928359/120103945-67ed0e00-c152-11eb-82e7-1dde4a486747.png) For the resistors, it helps to get some tweezers to keep them in place during soldering. Be sure to set the buck converter to 3.3V output before soldering the ESP.

Good luck, and enjoy!
