### ISSUE TITLE
Link to DirtyPCB is not accessible

### ISSUE THREAD

**Issue by RiRomain** [tjclement/esp-dimmer-hardware#6]
The link under **Ordering the board** redirect to dirty PCB shop but not to your design (http://dirtypcbs.com/store/designer/details/tjclement/1218/esp12-led-improved-zip)

I found the board in the dirty board shop at the address:
http://dirtypcbs.com/store/designer/details/tjclement/1329/5-esp8266-rgb-led-dimmer

BTW thanks for this great work I'll order one set :+1:

**Comment by tjclement** [comment]
Thanks for letting me know. Glad to hear you like it, have fun building them!
