### ISSUE TITLE
Flickering with PWM

### ISSUE THREAD

**Issue by TMaYaD** [tjclement/esp-dimmer-hardware#7]
How are you addressing the flickering due to lack of hardware pwm on esp8266?

**Comment by tjclement** [comment]
The esp does have hardware PWM, and it is supported in the Arduino API, the FreeRTOS release, and the esp IoT framework.

I'm currently using the Arduino API. It has a default PWM frequency of 1kHz, which is more than enough for simple, non-moving room lighting. You can increase the frequency, at cost of stepping precision (analogWriteFreq()).

**Comment by TMaYaD** [comment]
Oh, Thank you for making that clear.
