### ISSUE TITLE
five-channel version

### ISSUE THREAD

**Issue by renne** [tjclement/esp-dimmer-hardware#8]
As RGB-LEDs have low [CRI](https://en.wikipedia.org/wiki/Color_rendering_index) values I suggest a five-channel version for a RGB stripe + Dual-White stripe like the [H801](http://tinkerman.cat/closer-look-h801-led-wifi-controller/).

**Comment by tjclement** [comment]
Thanks, cool idea, but it would mean making it even larger. The goal of this unit is to have a super small, cheap, minimalistic dimmer. For 5 channels, the H801 you mentioned might be a more logical choice. It's not even that much more expensive than this unit.
